### ISSUE TITLE
Use index.js file in the controller, routes and models folder to export each file from inside of them

### ISSUE THREAD

**Issue by alanansari** [ayushmittal007/Pro-Go-Backend#1]
Like this:
<img width="189" alt="image" src="https://github.com/ayushmittal007/Pro-Go-Backend/assets/22475370/b7494dd8-5fbc-4362-a89b-5c1de2b74cfc">
![image](https://github.com/ayushmittal007/Pro-Go-Backend/assets/22475370/d1442b1e-273a-4bb6-b04f-3d20f804b567)
And then import like this:
<img width="257" alt="image" src="https://github.com/ayushmittal007/Pro-Go-Backend/assets/22475370/75d654d4-896f-4e77-9a91-2de0f2182a4b">

**Comment by ayushmittal007** [comment]
issue solved
branch directly merged into master
