### ISSUE TITLE
Structure responses properly

### ISSUE THREAD

**Issue by alanansari** [ayushmittal007/Pro-Go-Backend#2]
Like this:

{
    success: true/false,
    msg: "Some message sent for the use of frontend",
    data : {
       key: "object containing multiple key value pairs for data"
    }
}

<img width="334" alt="image" src="https://github.com/ayushmittal007/Pro-Go-Backend/assets/22475370/2354717c-925f-4b05-a9ea-90813a123404">

**Comment by ayushmittal007** [comment]
issue solved  
branch directly merged into master
